### ISSUE TITLE
JavaScript needs to re-init when switching tabs (like under a global set).

### ISSUE THREAD

**Issue by 23d1** [luwes/craft3-codemirror#7] opened 2018-10-20 05:31 UTC
As title. Doesn't layout properly, so it needs to init again to capture the input field and apply JS.

**Comment by richhayler** [comment] 2018-12-22 12:53
Give this a go, it worked for me....

edit your CodeMirror config file to include the following add-on and autoRefresh setting.

`return [
	"jsOptions" => [
        "autoRefresh" => true,
	],
	"addons" => [
		"display/autorefresh",
	]
];`

**Comment by luwes** [comment] 2018-12-24 02:33
Duplicate of #10

**Closed by luwes** 2018-12-24 02:33 UTC
