### ISSUE TITLE
[Bug] Content not shown when field is on a secondary tab

### ISSUE THREAD

**Issue by mattcdavis1** [luwes/craft3-codemirror#6] opened 2018-04-01 03:17 UTC
When a CodeMirror field is assigned to a non-default tab, the content of the field will not show until you click in the field.

**Comment by richhayler** [comment] 2018-12-22 12:53
Give this a go, it worked for me....

edit your CodeMirror config file to include the following add-on and autoRefresh setting.

`return [
	"jsOptions" => [
        "autoRefresh" => true,
	],
	"addons" => [
		"display/autorefresh",
	]
];`

**Comment by luwes** [comment] 2018-12-24 02:32
Duplicate of #10

**Closed by luwes** 2018-12-24 02:32 UTC
